package com.k1sak1.goetyawaken.client.animation.undead;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class TowerWraithAnimations {
        public static final AnimationDefinition ATTACK = AnimationDefinition.Builder.withLength(2.2F)
                        .addAnimation("head", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(10.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.15F, KeyframeAnimations.degreeVec(-45.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.35F, KeyframeAnimations.degreeVec(-45.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.45F, KeyframeAnimations.degreeVec(70.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.0F, KeyframeAnimations.degreeVec(80.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.2F, KeyframeAnimations.degreeVec(10.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("right_arm", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(-40.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.15F, KeyframeAnimations.degreeVec(-240.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.35F, KeyframeAnimations.degreeVec(-240.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.45F, KeyframeAnimations.degreeVec(-20.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.0F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.2F, KeyframeAnimations.degreeVec(-40.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("right_arm", new AnimationChannel(AnimationChannel.Targets.POSITION,
                                        new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.15F, KeyframeAnimations.posVec(0.0F, 2.0F, 2.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.35F, KeyframeAnimations.posVec(0.0F, 2.0F, 2.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.45F, KeyframeAnimations.posVec(0.0F, 2.0F, 2.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.2F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("body", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(7.5F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.15F, KeyframeAnimations.degreeVec(-7.5F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.35F, KeyframeAnimations.degreeVec(-7.5F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.45F, KeyframeAnimations.degreeVec(145.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.0F, KeyframeAnimations.degreeVec(60.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.5F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.2F, KeyframeAnimations.degreeVec(7.5F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("Ghost", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.2F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("Ghost", new AnimationChannel(AnimationChannel.Targets.POSITION,
                                        new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.15F, KeyframeAnimations.posVec(0.0F, 4.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.35F, KeyframeAnimations.posVec(0.0F, 4.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.45F, KeyframeAnimations.posVec(0.0F, -14.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.2F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("ribs", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.15F, KeyframeAnimations.degreeVec(-7.5F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.35F, KeyframeAnimations.degreeVec(-7.5F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.45F, KeyframeAnimations.degreeVec(-55.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.2F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("spine", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.15F, KeyframeAnimations.degreeVec(-15.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.45F, KeyframeAnimations.degreeVec(-30.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.2F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("left_arm", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(-40.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.15F, KeyframeAnimations.degreeVec(-250.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.35F, KeyframeAnimations.degreeVec(-250.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.45F, KeyframeAnimations.degreeVec(-35.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.0F, KeyframeAnimations.degreeVec(25.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.2F, KeyframeAnimations.degreeVec(-40.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("left_arm", new AnimationChannel(AnimationChannel.Targets.POSITION,
                                        new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.15F, KeyframeAnimations.posVec(0.0F, 2.0F, 2.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.35F, KeyframeAnimations.posVec(0.0F, 2.0F, 2.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.45F, KeyframeAnimations.posVec(0.0F, 2.0F, 2.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.2F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("right_bone", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(-12.5F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.25F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.35F, KeyframeAnimations.degreeVec(-12.5F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.8F, KeyframeAnimations.degreeVec(-12.5F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.2F, KeyframeAnimations.degreeVec(-12.5F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("right_bone", new AnimationChannel(AnimationChannel.Targets.POSITION,
                                        new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.2F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.25F, KeyframeAnimations.posVec(0.0F, -2.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.8F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.2F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("left_bone", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(-12.5F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.25F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.35F, KeyframeAnimations.degreeVec(-12.5F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.8F, KeyframeAnimations.degreeVec(-12.5F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.2F, KeyframeAnimations.degreeVec(-12.5F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("left_bone", new AnimationChannel(AnimationChannel.Targets.POSITION,
                                        new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.2F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.25F, KeyframeAnimations.posVec(0.0F, -2.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.8F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.2F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("robe", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.2F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .build();

        public static final AnimationDefinition PUKE = AnimationDefinition.Builder.withLength(3.5F)
                        .addAnimation("head", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(10.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.875F, KeyframeAnimations.degreeVec(45.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.125F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.2083F, KeyframeAnimations.degreeVec(0.0F, -15.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.2917F, KeyframeAnimations.degreeVec(0.0F, 20.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.375F, KeyframeAnimations.degreeVec(0.0F, -15.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.4583F, KeyframeAnimations.degreeVec(0.0F, 20.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.5417F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.625F, KeyframeAnimations.degreeVec(0.0F, -15.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.7083F, KeyframeAnimations.degreeVec(0.0F, 20.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.7917F, KeyframeAnimations.degreeVec(0.0F, -15.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.875F, KeyframeAnimations.degreeVec(0.0F, 20.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.9583F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.0417F, KeyframeAnimations.degreeVec(0.0F, -15.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.125F, KeyframeAnimations.degreeVec(0.0F, 20.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.2083F, KeyframeAnimations.degreeVec(0.0F, -15.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.2917F, KeyframeAnimations.degreeVec(0.0F, 20.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.375F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.4583F, KeyframeAnimations.degreeVec(0.0F, -15.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.5417F, KeyframeAnimations.degreeVec(0.0F, 20.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.625F, KeyframeAnimations.degreeVec(0.0F, -15.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.7083F, KeyframeAnimations.degreeVec(0.0F, 20.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.7917F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.875F, KeyframeAnimations.degreeVec(0.0F, -15.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.9583F, KeyframeAnimations.degreeVec(0.0F, 20.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(3.0417F, KeyframeAnimations.degreeVec(0.0F, -15.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(3.125F, KeyframeAnimations.degreeVec(0.0F, 20.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(3.2083F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(3.5F, KeyframeAnimations.degreeVec(10.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("right_arm", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(-40.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.25F, KeyframeAnimations.degreeVec(-45.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.875F,
                                                        KeyframeAnimations.degreeVec(-82.4596F, -31.7957F, -32.4897F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.0F, KeyframeAnimations.degreeVec(-45.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.125F,
                                                        KeyframeAnimations.degreeVec(43.6429F, -12.2766F, 12.5685F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.25F, KeyframeAnimations.degreeVec(75.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.4167F,
                                                        KeyframeAnimations.degreeVec(43.6429F, -12.2766F, 12.5685F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.6667F, KeyframeAnimations.degreeVec(75.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.8333F,
                                                        KeyframeAnimations.degreeVec(43.6429F, -12.2766F, 12.5685F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.0833F, KeyframeAnimations.degreeVec(75.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.25F, KeyframeAnimations.degreeVec(43.6429F, -12.2766F, 12.5685F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.5F, KeyframeAnimations.degreeVec(75.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.6667F,
                                                        KeyframeAnimations.degreeVec(43.6429F, -12.2766F, 12.5685F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.9167F, KeyframeAnimations.degreeVec(75.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(3.0833F,
                                                        KeyframeAnimations.degreeVec(43.6429F, -12.2766F, 12.5685F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(3.5F, KeyframeAnimations.degreeVec(-40.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("body", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(7.5F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.875F, KeyframeAnimations.degreeVec(12.5F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.125F, KeyframeAnimations.degreeVec(25.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.25F, KeyframeAnimations.degreeVec(35.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.4167F, KeyframeAnimations.degreeVec(25.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.5417F, KeyframeAnimations.degreeVec(25.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.6667F, KeyframeAnimations.degreeVec(35.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.8333F, KeyframeAnimations.degreeVec(25.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.9583F, KeyframeAnimations.degreeVec(25.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.0833F, KeyframeAnimations.degreeVec(35.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.25F, KeyframeAnimations.degreeVec(25.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.375F, KeyframeAnimations.degreeVec(25.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.5F, KeyframeAnimations.degreeVec(35.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.6667F, KeyframeAnimations.degreeVec(25.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.7917F, KeyframeAnimations.degreeVec(25.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.9167F, KeyframeAnimations.degreeVec(35.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(3.0833F, KeyframeAnimations.degreeVec(25.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(3.2083F, KeyframeAnimations.degreeVec(25.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(3.5F, KeyframeAnimations.degreeVec(7.5F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("left_arm", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(-40.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.25F, KeyframeAnimations.degreeVec(-45.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.875F,
                                                        KeyframeAnimations.degreeVec(-82.4596F, 31.7957F, 32.4897F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.0F, KeyframeAnimations.degreeVec(-45.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.125F,
                                                        KeyframeAnimations.degreeVec(43.6429F, 12.2766F, -12.5685F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.25F, KeyframeAnimations.degreeVec(75.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.4167F,
                                                        KeyframeAnimations.degreeVec(43.6429F, 12.2766F, -12.5685F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.6667F, KeyframeAnimations.degreeVec(75.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.8333F,
                                                        KeyframeAnimations.degreeVec(43.6429F, 12.2766F, -12.5685F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.0833F, KeyframeAnimations.degreeVec(75.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.25F, KeyframeAnimations.degreeVec(43.6429F, 12.2766F, -12.5685F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.5F, KeyframeAnimations.degreeVec(75.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.6667F,
                                                        KeyframeAnimations.degreeVec(43.6429F, 12.2766F, -12.5685F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.9167F, KeyframeAnimations.degreeVec(75.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(3.0833F,
                                                        KeyframeAnimations.degreeVec(43.6429F, 12.2766F, -12.5685F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(3.5F, KeyframeAnimations.degreeVec(-40.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("right_bone", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(-12.5F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.25F, KeyframeAnimations.degreeVec(-12.5F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(3.0833F, KeyframeAnimations.degreeVec(-12.5F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(3.5F, KeyframeAnimations.degreeVec(-12.5F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("right_bone", new AnimationChannel(AnimationChannel.Targets.POSITION,
                                        new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(3.5F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("left_bone", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(-12.5F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.25F, KeyframeAnimations.degreeVec(-12.5F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(3.0833F, KeyframeAnimations.degreeVec(-12.5F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(3.5F, KeyframeAnimations.degreeVec(-12.5F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("left_bone", new AnimationChannel(AnimationChannel.Targets.POSITION,
                                        new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(3.5F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("Ghost", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(3.5F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("Ghost", new AnimationChannel(AnimationChannel.Targets.POSITION,
                                        new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(3.5F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("ribs", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(3.5F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("spine", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(3.5F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("robe", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(3.5F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .build();

        public static final AnimationDefinition TELEPORT_OUT = AnimationDefinition.Builder.withLength(1.5834333f)
                        .addAnimation("Ghost",
                                        new AnimationChannel(AnimationChannel.Targets.POSITION,
                                                        new Keyframe(0f, KeyframeAnimations.posVec(0f, -13f, 0f),
                                                                        AnimationChannel.Interpolations.CATMULLROM),
                                                        new Keyframe(0.20834334f,
                                                                        KeyframeAnimations.posVec(0f, -4.55f, 4f),
                                                                        AnimationChannel.Interpolations.CATMULLROM),
                                                        new Keyframe(0.8343334f, KeyframeAnimations.posVec(0f, 2f, 0f),
                                                                        AnimationChannel.Interpolations.CATMULLROM),
                                                        new Keyframe(1.25f, KeyframeAnimations.posVec(0f, 2f, 0f),
                                                                        AnimationChannel.Interpolations.CATMULLROM),
                                                        new Keyframe(1.5834333f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("head",
                                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                                        new Keyframe(0f, KeyframeAnimations.degreeVec(90f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.CATMULLROM),
                                                        new Keyframe(0.4167667f,
                                                                        KeyframeAnimations.degreeVec(20f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.CATMULLROM),
                                                        new Keyframe(0.8343334f,
                                                                        KeyframeAnimations.degreeVec(10f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.CATMULLROM),
                                                        new Keyframe(1.5834333f,
                                                                        KeyframeAnimations.degreeVec(17.5f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("right_arm",
                                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                                        new Keyframe(0f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.CATMULLROM),
                                                        new Keyframe(0.4167667f,
                                                                        KeyframeAnimations.degreeVec(-115f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.CATMULLROM),
                                                        new Keyframe(0.625f,
                                                                        KeyframeAnimations.degreeVec(-125f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.CATMULLROM),
                                                        new Keyframe(0.8343334f,
                                                                        KeyframeAnimations.degreeVec(-150f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.CATMULLROM),
                                                        new Keyframe(1.5834333f,
                                                                        KeyframeAnimations.degreeVec(-40f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("right_bone",
                                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                                        new Keyframe(0f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.CATMULLROM),
                                                        new Keyframe(1.5834333f,
                                                                        KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("left_arm",
                                        new AnimationChannel(AnimationChannel.Targets.POSITION,
                                                        new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.CATMULLROM),
                                                        new Keyframe(0.8343334f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("left_arm",
                                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                                        new Keyframe(0f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.CATMULLROM),
                                                        new Keyframe(0.4167667f,
                                                                        KeyframeAnimations.degreeVec(-125f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.CATMULLROM),
                                                        new Keyframe(0.8343334f,
                                                                        KeyframeAnimations.degreeVec(-150f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.CATMULLROM),
                                                        new Keyframe(1.5834333f,
                                                                        KeyframeAnimations.degreeVec(-40f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("left_bone",
                                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                                        new Keyframe(0f, KeyframeAnimations.degreeVec(-12.5f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.CATMULLROM),
                                                        new Keyframe(1.5834333f,
                                                                        KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("body",
                                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                                        new Keyframe(0f, KeyframeAnimations.degreeVec(15f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.CATMULLROM),
                                                        new Keyframe(0.4167667f,
                                                                        KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.CATMULLROM),
                                                        new Keyframe(0.8343334f,
                                                                        KeyframeAnimations.degreeVec(2.5f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.CATMULLROM),
                                                        new Keyframe(1.5834333f,
                                                                        KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("ribs",
                                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                                        new Keyframe(0f, KeyframeAnimations.degreeVec(60f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.CATMULLROM),
                                                        new Keyframe(0.4167667f,
                                                                        KeyframeAnimations.degreeVec(15f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.CATMULLROM),
                                                        new Keyframe(0.8343334f,
                                                                        KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.CATMULLROM),
                                                        new Keyframe(1.5834333f,
                                                                        KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("spine",
                                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                                        new Keyframe(0f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.CATMULLROM),
                                                        new Keyframe(0.4167667f,
                                                                        KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.CATMULLROM),
                                                        new Keyframe(0.8343334f,
                                                                        KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.CATMULLROM),
                                                        new Keyframe(1.5834333f,
                                                                        KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("robe",
                                        new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                                        new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.CATMULLROM),
                                                        new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.CATMULLROM),
                                                        new Keyframe(1.5834333f,
                                                                        KeyframeAnimations.degreeVec(10f, 0f, 0f),
                                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .build();

        public static final AnimationDefinition ACID = AnimationDefinition.Builder.withLength(2.2F)
                        .addAnimation("Ghost", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.3F, KeyframeAnimations.degreeVec(75.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.55F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.75F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.2F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("Ghost", new AnimationChannel(AnimationChannel.Targets.POSITION,
                                        new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.3F, KeyframeAnimations.posVec(0.0F, 8.0F, 24.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.55F, KeyframeAnimations.posVec(0.0F, 2.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.75F, KeyframeAnimations.posVec(0.0F, -2.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.2F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("head", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(10.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.3F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.55F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.0F, KeyframeAnimations.degreeVec(-20.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.75F, KeyframeAnimations.degreeVec(10.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.2F, KeyframeAnimations.degreeVec(10.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("right_arm", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(-40.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.3F, KeyframeAnimations.degreeVec(7.5F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.55F, KeyframeAnimations.degreeVec(-190.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.0F, KeyframeAnimations.degreeVec(-240.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.75F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.2F, KeyframeAnimations.degreeVec(-40.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("right_bone", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(-12.5F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.3F, KeyframeAnimations.degreeVec(5.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.55F, KeyframeAnimations.degreeVec(10.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.75F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.2F, KeyframeAnimations.degreeVec(-12.5F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("right_bone", new AnimationChannel(AnimationChannel.Targets.POSITION,
                                        new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.3F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.55F, KeyframeAnimations.posVec(0.0F, -1.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.75F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.2F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("left_arm", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(-40.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.3F, KeyframeAnimations.degreeVec(7.5F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.55F, KeyframeAnimations.degreeVec(-190.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.0F, KeyframeAnimations.degreeVec(-245.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.75F, KeyframeAnimations.degreeVec(-15.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.2F, KeyframeAnimations.degreeVec(-40.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("left_bone", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(-12.5F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.3F, KeyframeAnimations.degreeVec(5.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.55F, KeyframeAnimations.degreeVec(5.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.75F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.2F, KeyframeAnimations.degreeVec(-12.5F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("left_bone", new AnimationChannel(AnimationChannel.Targets.POSITION,
                                        new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.3F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.55F, KeyframeAnimations.posVec(0.0F, -1.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.75F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.2F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("body", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(7.5F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.3F, KeyframeAnimations.degreeVec(-20.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.55F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.0F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.75F, KeyframeAnimations.degreeVec(5.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.2F, KeyframeAnimations.degreeVec(7.5F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("ribs", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.3F, KeyframeAnimations.degreeVec(-5.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.55F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.2F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("spine", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.3F, KeyframeAnimations.degreeVec(-2.5F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.55F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.2F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("robe", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.3F, KeyframeAnimations.degreeVec(5.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.55F, KeyframeAnimations.degreeVec(57.5F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.75F, KeyframeAnimations.degreeVec(10.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(2.2F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .build();
        public static final AnimationDefinition MODECHANGE = AnimationDefinition.Builder.withLength(1.7857F)
                        .addAnimation("Ghost", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.LINEAR),
                                        new Keyframe(0.2646F, KeyframeAnimations.degreeVec(-12.5F, -25.0F, 0.0F),
                                                        AnimationChannel.Interpolations.LINEAR),
                                        new Keyframe(0.463F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.LINEAR),
                                        new Keyframe(0.9921F, KeyframeAnimations.degreeVec(2.0F, 320.0F, 0.0F),
                                                        AnimationChannel.Interpolations.LINEAR),
                                        new Keyframe(1.455F, KeyframeAnimations.degreeVec(4.5F, 355.0F, 0.0F),
                                                        AnimationChannel.Interpolations.LINEAR),
                                        new Keyframe(1.7857F, KeyframeAnimations.degreeVec(0.0F, 360.0F, 0.0F),
                                                        AnimationChannel.Interpolations.LINEAR)))
                        .addAnimation("Ghost", new AnimationChannel(AnimationChannel.Targets.POSITION,
                                        new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.LINEAR),
                                        new Keyframe(0.2646F, KeyframeAnimations.posVec(0.0F, -1.5F, 0.0F),
                                                        AnimationChannel.Interpolations.LINEAR),
                                        new Keyframe(0.6614F, KeyframeAnimations.posVec(0.0F, 2.0F, 0.0F),
                                                        AnimationChannel.Interpolations.LINEAR),
                                        new Keyframe(1.1905F, KeyframeAnimations.posVec(0.0F, -0.5F, 0.0F),
                                                        AnimationChannel.Interpolations.LINEAR),
                                        new Keyframe(1.7857F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.LINEAR)))
                        .addAnimation("head", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(10.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.LINEAR),
                                        new Keyframe(0.2646F, KeyframeAnimations.degreeVec(26.4467F, -8.5828F, 4.6512F),
                                                        AnimationChannel.Interpolations.LINEAR),
                                        new Keyframe(0.463F, KeyframeAnimations.degreeVec(-15.0F, 12.5F, -0.5F),
                                                        AnimationChannel.Interpolations.LINEAR),
                                        new Keyframe(0.6614F, KeyframeAnimations.degreeVec(-15.0F, 12.5F, -0.5F),
                                                        AnimationChannel.Interpolations.LINEAR),
                                        new Keyframe(0.9921F, KeyframeAnimations.degreeVec(-15.0F, 15.0F, -1.0F),
                                                        AnimationChannel.Interpolations.LINEAR),
                                        new Keyframe(1.1905F, KeyframeAnimations.degreeVec(6.0F, 8.0F, -1.0F),
                                                        AnimationChannel.Interpolations.LINEAR),
                                        new Keyframe(1.455F, KeyframeAnimations.degreeVec(-0.6487F, 8.4283F, -0.4852F),
                                                        AnimationChannel.Interpolations.LINEAR),
                                        new Keyframe(1.6534F, KeyframeAnimations.degreeVec(7.5F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.LINEAR),
                                        new Keyframe(1.7857F, KeyframeAnimations.degreeVec(10.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.LINEAR)))
                        .addAnimation("head", new AnimationChannel(AnimationChannel.Targets.POSITION,
                                        new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.LINEAR)))
                        .addAnimation("right_arm", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(-40.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.LINEAR),
                                        new Keyframe(0.2646F,
                                                        KeyframeAnimations.degreeVec(-25.4163F, -32.8674F, -9.6506F),
                                                        AnimationChannel.Interpolations.LINEAR),
                                        new Keyframe(0.3307F,
                                                        KeyframeAnimations.degreeVec(-48.7473F, 33.4887F, -26.2307F),
                                                        AnimationChannel.Interpolations.LINEAR),
                                        new Keyframe(0.3968F,
                                                        KeyframeAnimations.degreeVec(-113.3081F, 49.4325F, -66.6335F),
                                                        AnimationChannel.Interpolations.LINEAR),
                                        new Keyframe(0.463F,
                                                        KeyframeAnimations.degreeVec(-159.3793F, 67.6258F, -77.8648F),
                                                        AnimationChannel.Interpolations.LINEAR),
                                        new Keyframe(0.9921F, KeyframeAnimations.degreeVec(-87.5F, 85.0F, 7.5F),
                                                        AnimationChannel.Interpolations.LINEAR),
                                        new Keyframe(1.5873F, KeyframeAnimations.degreeVec(-45.0F, 2.0F, 0.0F),
                                                        AnimationChannel.Interpolations.LINEAR),
                                        new Keyframe(1.7857F, KeyframeAnimations.degreeVec(-40.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.LINEAR)))
                        .addAnimation("right_arm", new AnimationChannel(AnimationChannel.Targets.POSITION,
                                        new Keyframe(0.2646F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.LINEAR),
                                        new Keyframe(0.5952F, KeyframeAnimations.posVec(-1.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.LINEAR),
                                        new Keyframe(1.3889F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.LINEAR),
                                        new Keyframe(1.5873F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.LINEAR)))
                        .addAnimation("right_bone", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(-12.5F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.2646F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.2566F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.7196F, KeyframeAnimations.degreeVec(-12.5F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("left_arm", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(-40.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.LINEAR),
                                        new Keyframe(0.2646F,
                                                        KeyframeAnimations.degreeVec(16.8953F, -9.7456F, -34.7987F),
                                                        AnimationChannel.Interpolations.LINEAR),
                                        new Keyframe(0.5291F, KeyframeAnimations.degreeVec(-87.5F, -85.0F, -7.5F),
                                                        AnimationChannel.Interpolations.LINEAR),
                                        new Keyframe(0.9921F, KeyframeAnimations.degreeVec(-87.5F, -85.0F, -7.5F),
                                                        AnimationChannel.Interpolations.LINEAR),
                                        new Keyframe(1.5873F, KeyframeAnimations.degreeVec(-45.0F, -2.0F, 0.0F),
                                                        AnimationChannel.Interpolations.LINEAR),
                                        new Keyframe(1.7857F, KeyframeAnimations.degreeVec(-40.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.LINEAR)))
                        .addAnimation("left_arm", new AnimationChannel(AnimationChannel.Targets.POSITION,
                                        new Keyframe(0.2646F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.LINEAR),
                                        new Keyframe(0.5952F, KeyframeAnimations.posVec(-1.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.LINEAR),
                                        new Keyframe(1.3889F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.LINEAR),
                                        new Keyframe(1.5873F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.LINEAR)))
                        .addAnimation("left_bone", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(-12.5F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(0.2646F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.2566F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM),
                                        new Keyframe(1.7196F, KeyframeAnimations.degreeVec(-12.5F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.CATMULLROM)))
                        .addAnimation("body", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(7.5F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.LINEAR)))
                        .addAnimation("body", new AnimationChannel(AnimationChannel.Targets.POSITION,
                                        new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.LINEAR),
                                        new Keyframe(0.1984F, KeyframeAnimations.posVec(0.0F, 1.5F, 0.0F),
                                                        AnimationChannel.Interpolations.LINEAR),
                                        new Keyframe(0.463F, KeyframeAnimations.posVec(0.0F, 1.5F, 0.0F),
                                                        AnimationChannel.Interpolations.LINEAR),
                                        new Keyframe(0.5291F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.LINEAR)))
                        .addAnimation("robe", new AnimationChannel(AnimationChannel.Targets.ROTATION,
                                        new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.LINEAR),
                                        new Keyframe(0.3307F, KeyframeAnimations.degreeVec(12.5F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.LINEAR),
                                        new Keyframe(0.8598F, KeyframeAnimations.degreeVec(12.0F, 0.0F, 7.5F),
                                                        AnimationChannel.Interpolations.LINEAR),
                                        new Keyframe(1.0582F, KeyframeAnimations.degreeVec(22.213F, 0.0F, 4.3054F),
                                                        AnimationChannel.Interpolations.LINEAR),
                                        new Keyframe(1.3228F, KeyframeAnimations.degreeVec(12.5F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.LINEAR),
                                        new Keyframe(1.7857F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
                                                        AnimationChannel.Interpolations.LINEAR)))
                        .build();
}
