package com.k1sak1.goetyawaken.client.animation;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class GiantGhastAnimation {
	public static final AnimationDefinition IDLE = AnimationDefinition.Builder.withLength(7.0F).looping()

			.addAnimation("body_main", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(-0.19F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.0833F, KeyframeAnimations.degreeVec(-0.21F, 0.0F, -0.08F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.1667F, KeyframeAnimations.degreeVec(-0.22F, 0.0F, -0.15F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.25F, KeyframeAnimations.degreeVec(-0.22F, 0.0F, -0.23F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.3333F, KeyframeAnimations.degreeVec(-0.19F, 0.0F, -0.31F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.4167F, KeyframeAnimations.degreeVec(-0.1F, 0.0F, -0.39F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5F, KeyframeAnimations.degreeVec(0.02F, 0.0F, -0.46F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5833F, KeyframeAnimations.degreeVec(0.17F, 0.0F, -0.53F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.6667F, KeyframeAnimations.degreeVec(0.33F, 0.0F, -0.59F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.75F, KeyframeAnimations.degreeVec(0.49F, 0.0F, -0.65F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.8333F, KeyframeAnimations.degreeVec(0.64F, 0.0F, -0.69F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.9167F, KeyframeAnimations.degreeVec(0.78F, 0.0F, -0.71F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.0F, KeyframeAnimations.degreeVec(0.9F, 0.0F, -0.72F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.0833F, KeyframeAnimations.degreeVec(0.99F, 0.0F, -0.67F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.1667F, KeyframeAnimations.degreeVec(1.06F, 0.0F, -0.53F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.25F, KeyframeAnimations.degreeVec(1.11F, 0.0F, -0.32F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.3333F, KeyframeAnimations.degreeVec(1.12F, 0.0F, -0.08F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.4167F, KeyframeAnimations.degreeVec(1.11F, 0.0F, 0.17F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.5F, KeyframeAnimations.degreeVec(1.09F, 0.0F, 0.42F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.5833F, KeyframeAnimations.degreeVec(1.05F, 0.0F, 0.64F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.6667F, KeyframeAnimations.degreeVec(1.0F, 0.0F, 0.84F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.75F, KeyframeAnimations.degreeVec(0.94F, 0.0F, 1.01F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.8333F, KeyframeAnimations.degreeVec(0.87F, 0.0F, 1.16F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.9167F, KeyframeAnimations.degreeVec(0.81F, 0.0F, 1.27F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(2.0F, KeyframeAnimations.degreeVec(0.73F, 0.0F, 1.36F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(2.0833F, KeyframeAnimations.degreeVec(0.66F, 0.0F, 1.42F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(2.125F, KeyframeAnimations.degreeVec(0.62F, 0.0F, 1.44F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(2.1667F, KeyframeAnimations.degreeVec(0.58F, 0.0F, 1.45F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(2.25F, KeyframeAnimations.degreeVec(0.51F, 0.0F, 1.45F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(2.3333F, KeyframeAnimations.degreeVec(0.43F, 0.0F, 1.42F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(2.4167F, KeyframeAnimations.degreeVec(0.35F, 0.0F, 1.36F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(2.5F, KeyframeAnimations.degreeVec(0.28F, 0.0F, 1.28F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(2.5833F, KeyframeAnimations.degreeVec(0.2F, 0.0F, 1.18F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(2.6667F, KeyframeAnimations.degreeVec(0.13F, 0.0F, 1.05F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(2.75F, KeyframeAnimations.degreeVec(0.06F, 0.0F, 0.92F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(2.8333F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.77F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(2.9167F, KeyframeAnimations.degreeVec(-0.06F, 0.0F, 0.62F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(3.0F, KeyframeAnimations.degreeVec(-0.11F, 0.0F, 0.46F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(3.0833F, KeyframeAnimations.degreeVec(-0.15F, 0.0F, 0.3F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(3.1667F, KeyframeAnimations.degreeVec(-0.19F, 0.0F, 0.14F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(3.25F, KeyframeAnimations.degreeVec(-0.22F, 0.0F, -0.02F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(3.3333F, KeyframeAnimations.degreeVec(-0.23F, 0.0F, -0.16F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(3.4167F, KeyframeAnimations.degreeVec(-0.23F, 0.0F, -0.31F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(3.5F, KeyframeAnimations.degreeVec(-0.23F, 0.0F, -0.43F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(3.5833F, KeyframeAnimations.degreeVec(-0.21F, 0.0F, -0.55F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(3.6667F, KeyframeAnimations.degreeVec(-0.19F, 0.0F, -0.65F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(3.75F, KeyframeAnimations.degreeVec(-0.16F, 0.0F, -0.73F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(3.8333F, KeyframeAnimations.degreeVec(-0.12F, 0.0F, -0.79F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(3.9167F, KeyframeAnimations.degreeVec(-0.08F, 0.0F, -0.83F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(4.0F, KeyframeAnimations.degreeVec(-0.02F, 0.0F, -0.84F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(4.0417F, KeyframeAnimations.degreeVec(0.005F, 0.0F, -0.84F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(4.0833F, KeyframeAnimations.degreeVec(0.03F, 0.0F, -0.83F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(4.1667F, KeyframeAnimations.degreeVec(0.09F, 0.0F, -0.81F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(4.25F, KeyframeAnimations.degreeVec(0.15F, 0.0F, -0.77F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(4.3333F, KeyframeAnimations.degreeVec(0.2F, 0.0F, -0.71F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(4.4167F, KeyframeAnimations.degreeVec(0.25F, 0.0F, -0.63F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(4.5F, KeyframeAnimations.degreeVec(0.29F, 0.0F, -0.53F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(4.5833F, KeyframeAnimations.degreeVec(0.32F, 0.0F, -0.4F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(4.6667F, KeyframeAnimations.degreeVec(0.33F, 0.0F, -0.25F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(4.75F, KeyframeAnimations.degreeVec(0.33F, 0.0F, -0.1F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(4.8333F, KeyframeAnimations.degreeVec(0.32F, 0.0F, 0.04F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(4.9167F, KeyframeAnimations.degreeVec(0.31F, 0.0F, 0.17F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(5.0F, KeyframeAnimations.degreeVec(0.29F, 0.0F, 0.28F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(5.0833F, KeyframeAnimations.degreeVec(0.26F, 0.0F, 0.36F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(5.1667F, KeyframeAnimations.degreeVec(0.23F, 0.0F, 0.44F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(5.25F, KeyframeAnimations.degreeVec(0.2F, 0.0F, 0.5F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(5.3333F, KeyframeAnimations.degreeVec(0.17F, 0.0F, 0.54F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(5.4167F, KeyframeAnimations.degreeVec(0.15F, 0.0F, 0.58F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(5.4583F, KeyframeAnimations.degreeVec(0.135F, 0.0F, 0.6F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(5.5F, KeyframeAnimations.degreeVec(0.12F, 0.0F, 0.61F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(5.5833F, KeyframeAnimations.degreeVec(0.1F, 0.0F, 0.63F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(5.6667F, KeyframeAnimations.degreeVec(0.07F, 0.0F, 0.64F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(5.75F, KeyframeAnimations.degreeVec(0.05F, 0.0F, 0.65F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(5.8333F, KeyframeAnimations.degreeVec(0.04F, 0.0F, 0.65F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(5.9167F, KeyframeAnimations.degreeVec(0.02F, 0.0F, 0.65F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(6.0F, KeyframeAnimations.degreeVec(0.01F, 0.0F, 0.65F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(6.0833F, KeyframeAnimations.degreeVec(0.01F, 0.0F, 0.63F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(6.1667F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.61F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(6.25F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.58F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(6.3333F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.54F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(6.4167F, KeyframeAnimations.degreeVec(-0.01F, 0.0F, 0.49F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(6.5F, KeyframeAnimations.degreeVec(-0.03F, 0.0F, 0.44F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(6.5833F, KeyframeAnimations.degreeVec(-0.05F, 0.0F, 0.38F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(6.6667F, KeyframeAnimations.degreeVec(-0.07F, 0.0F, 0.31F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(6.75F, KeyframeAnimations.degreeVec(-0.1F, 0.0F, 0.24F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(6.8333F, KeyframeAnimations.degreeVec(-0.13F, 0.0F, 0.16F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(6.9167F, KeyframeAnimations.degreeVec(-0.17F, 0.0F, 0.08F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(7.0F, KeyframeAnimations.degreeVec(-0.19F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("body_main", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -0.1348F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5417F, KeyframeAnimations.posVec(0.0F, 0.5726F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.8333F, KeyframeAnimations.posVec(0.0F, 0.902F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.0417F, KeyframeAnimations.posVec(0.0F, 1.0853F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.25F, KeyframeAnimations.posVec(0.0F, 1.2075F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.4583F, KeyframeAnimations.posVec(0.0F, 1.2588F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.5F, KeyframeAnimations.posVec(0.0F, 1.2603F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.5417F, KeyframeAnimations.posVec(0.0F, 1.2541F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.5833F, KeyframeAnimations.posVec(0.0F, 1.2363F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.625F, KeyframeAnimations.posVec(0.0F, 1.2072F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.6667F, KeyframeAnimations.posVec(0.0F, 1.1677F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.7083F, KeyframeAnimations.posVec(0.0F, 1.1184F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.75F, KeyframeAnimations.posVec(0.0F, 1.0599F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.7917F, KeyframeAnimations.posVec(0.0F, 0.9932F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.8333F, KeyframeAnimations.posVec(0.0F, 0.9188F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.875F, KeyframeAnimations.posVec(0.0F, 0.8377F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.9167F, KeyframeAnimations.posVec(0.0F, 0.7505F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(2.2917F, KeyframeAnimations.posVec(0.0F, -0.1697F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(2.4583F, KeyframeAnimations.posVec(0.0F, -0.5621F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(2.5F, KeyframeAnimations.posVec(0.0F, -0.6503F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(2.5417F, KeyframeAnimations.posVec(0.0F, -0.7332F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(2.5833F, KeyframeAnimations.posVec(0.0F, -0.8104F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(2.625F, KeyframeAnimations.posVec(0.0F, -0.8813F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(2.6667F, KeyframeAnimations.posVec(0.0F, -0.9455F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(2.7083F, KeyframeAnimations.posVec(0.0F, -1.0023F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(2.75F, KeyframeAnimations.posVec(0.0F, -1.0515F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(2.7917F, KeyframeAnimations.posVec(0.0F, -1.0927F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(2.8333F, KeyframeAnimations.posVec(0.0F, -1.1253F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(2.875F, KeyframeAnimations.posVec(0.0F, -1.1493F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(2.9167F, KeyframeAnimations.posVec(0.0F, -1.1642F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(2.9583F, KeyframeAnimations.posVec(0.0F, -1.1698F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(3.0F, KeyframeAnimations.posVec(0.0F, -1.1658F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(3.0417F, KeyframeAnimations.posVec(0.0F, -1.1522F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(3.0833F, KeyframeAnimations.posVec(0.0F, -1.1293F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(3.125F, KeyframeAnimations.posVec(0.0F, -1.0969F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(3.1667F, KeyframeAnimations.posVec(0.0F, -1.0553F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(3.2083F, KeyframeAnimations.posVec(0.0F, -1.0047F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(3.25F, KeyframeAnimations.posVec(0.0F, -0.9454F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(3.2917F, KeyframeAnimations.posVec(0.0F, -0.8778F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(3.3333F, KeyframeAnimations.posVec(0.0F, -0.8022F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(3.375F, KeyframeAnimations.posVec(0.0F, -0.7191F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(3.4167F, KeyframeAnimations.posVec(0.0F, -0.6291F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(3.4583F, KeyframeAnimations.posVec(0.0F, -0.533F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(3.5F, KeyframeAnimations.posVec(0.0F, -0.4313F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(3.7917F, KeyframeAnimations.posVec(0.0F, 0.3552F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(3.875F, KeyframeAnimations.posVec(0.0F, 0.5721F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(3.9167F, KeyframeAnimations.posVec(0.0F, 0.6737F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(3.9583F, KeyframeAnimations.posVec(0.0F, 0.7692F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(4.0F, KeyframeAnimations.posVec(0.0F, 0.8578F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(4.0417F, KeyframeAnimations.posVec(0.0F, 0.9384F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(4.0833F, KeyframeAnimations.posVec(0.0F, 1.0102F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(4.125F, KeyframeAnimations.posVec(0.0F, 1.0725F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(4.1667F, KeyframeAnimations.posVec(0.0F, 1.1245F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(4.2083F, KeyframeAnimations.posVec(0.0F, 1.1657F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(4.25F, KeyframeAnimations.posVec(0.0F, 1.1955F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(4.2917F, KeyframeAnimations.posVec(0.0F, 1.2136F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(4.3333F, KeyframeAnimations.posVec(0.0F, 1.2197F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(4.375F, KeyframeAnimations.posVec(0.0F, 1.2123F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(4.4167F, KeyframeAnimations.posVec(0.0F, 1.1903F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(4.4583F, KeyframeAnimations.posVec(0.0F, 1.1544F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(4.5F, KeyframeAnimations.posVec(0.0F, 1.1053F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(4.5417F, KeyframeAnimations.posVec(0.0F, 1.0437F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(4.5833F, KeyframeAnimations.posVec(0.0F, 0.9704F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(4.625F, KeyframeAnimations.posVec(0.0F, 0.8863F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(4.6667F, KeyframeAnimations.posVec(0.0F, 0.7924F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(4.7083F, KeyframeAnimations.posVec(0.0F, 0.6896F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(4.75F, KeyframeAnimations.posVec(0.0F, 0.5789F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(4.7917F, KeyframeAnimations.posVec(0.0F, 0.4615F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(4.8333F, KeyframeAnimations.posVec(0.0F, 0.3383F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(5.0833F, KeyframeAnimations.posVec(0.0F, -0.4582F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(5.2083F, KeyframeAnimations.posVec(0.0F, -0.8439F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(5.25F, KeyframeAnimations.posVec(0.0F, -0.9639F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(5.2917F, KeyframeAnimations.posVec(0.0F, -1.0779F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(5.3333F, KeyframeAnimations.posVec(0.0F, -1.1853F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(5.375F, KeyframeAnimations.posVec(0.0F, -1.2852F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(5.4167F, KeyframeAnimations.posVec(0.0F, -1.3769F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(5.4583F, KeyframeAnimations.posVec(0.0F, -1.4598F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(5.5F, KeyframeAnimations.posVec(0.0F, -1.5333F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(5.5417F, KeyframeAnimations.posVec(0.0F, -1.5969F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(5.5833F, KeyframeAnimations.posVec(0.0F, -1.6499F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(5.625F, KeyframeAnimations.posVec(0.0F, -1.6922F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(5.6667F, KeyframeAnimations.posVec(0.0F, -1.7231F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(5.7083F, KeyframeAnimations.posVec(0.0F, -1.7426F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(5.75F, KeyframeAnimations.posVec(0.0F, -1.7503F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(5.9167F, KeyframeAnimations.posVec(0.0F, -1.7225F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(6.0833F, KeyframeAnimations.posVec(0.0F, -1.6263F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(6.25F, KeyframeAnimations.posVec(0.0F, -1.4634F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(6.4167F, KeyframeAnimations.posVec(0.0F, -1.2377F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(6.625F, KeyframeAnimations.posVec(0.0F, -0.8801F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(6.9583F, KeyframeAnimations.posVec(0.0F, -0.2156F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(7.0F, KeyframeAnimations.posVec(0.0F, -0.1348F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("eye_main1", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(1.9167F, KeyframeAnimations.posVec(0.0F, 0.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.9583F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("eye_main1", new AnimationChannel(AnimationChannel.Targets.SCALE,
					new Keyframe(0.0F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.9583F, KeyframeAnimations.scaleVec(1.0F, 0.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(2.2083F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(5.7083F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(6.0F, KeyframeAnimations.scaleVec(1.0F, 0.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("eye_main2", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("mouth", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.build();

}