package com.k1sak1.goetyawaken.client.animation;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class TowerGuardAnimation {
	public static final AnimationDefinition IDLE = AnimationDefinition.Builder.withLength(4.5F).looping()
			.addAnimation("Body", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.75F, KeyframeAnimations.degreeVec(2.5F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.5F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.25F, KeyframeAnimations.degreeVec(2.5F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.75F, KeyframeAnimations.degreeVec(2.5F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.5F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("Head", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(1.25F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.5F, KeyframeAnimations.degreeVec(0.0F, 27.5F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.7083F, KeyframeAnimations.degreeVec(0.0F, 27.5F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.75F, KeyframeAnimations.degreeVec(0.0F, 27.5F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(2.0F, KeyframeAnimations.degreeVec(0.0F, 27.5F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(2.25F, KeyframeAnimations.degreeVec(0.0F, -27.5F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.4583F, KeyframeAnimations.degreeVec(0.0F, -27.5F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(2.5F, KeyframeAnimations.degreeVec(0.0F, -27.5F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(3.375F, KeyframeAnimations.degreeVec(0.0F, -27.5F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(3.625F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.8333F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(3.875F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("Cape", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(15.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("RightArm", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(6.246F, 19.0377F, 18.5484F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.0F, KeyframeAnimations.degreeVec(-1.254F, 19.0377F, 18.5484F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.5F, KeyframeAnimations.degreeVec(6.246F, 19.0377F, 18.5484F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.5F, KeyframeAnimations.degreeVec(-1.254F, 19.0377F, 18.5484F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.0F, KeyframeAnimations.degreeVec(6.246F, 19.0377F, 18.5484F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.0F, KeyframeAnimations.degreeVec(-1.254F, 19.0377F, 18.5484F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.5F, KeyframeAnimations.degreeVec(6.246F, 19.0377F, 18.5484F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("LeftArm", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(-62.5F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.75F, KeyframeAnimations.degreeVec(-65.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.5F, KeyframeAnimations.degreeVec(-62.5F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.25F, KeyframeAnimations.degreeVec(-65.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.0F, KeyframeAnimations.degreeVec(-62.5F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.75F, KeyframeAnimations.degreeVec(-65.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.5F, KeyframeAnimations.degreeVec(-62.5F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("RightLeg", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(6.5455F, 16.9967F, 5.209F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.25F, KeyframeAnimations.degreeVec(6.5455F, 16.9967F, 5.209F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("RightLeg", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("LeftLeg", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, -7.5F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("LeftLeg", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(1.0F, 0.0F, -2.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("r_eye", new AnimationChannel(AnimationChannel.Targets.SCALE,
					new Keyframe(0.5F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.625F, KeyframeAnimations.scaleVec(1.0F, 0.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.75F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.375F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.5F, KeyframeAnimations.scaleVec(1.0F, 0.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.625F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(2.75F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(2.875F, KeyframeAnimations.scaleVec(1.0F, 0.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(3.0F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("r_pupil", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(1.25F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.5F, KeyframeAnimations.posVec(-1.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(2.0F, KeyframeAnimations.posVec(-1.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(2.25F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("l_eye", new AnimationChannel(AnimationChannel.Targets.SCALE,
					new Keyframe(0.5F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.625F, KeyframeAnimations.scaleVec(1.0F, 0.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.75F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.375F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.5F, KeyframeAnimations.scaleVec(1.0F, 0.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.625F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(2.75F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(2.875F, KeyframeAnimations.scaleVec(1.0F, 0.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(3.0F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("l_pupil", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(2.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(2.25F, KeyframeAnimations.posVec(1.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(2.75F, KeyframeAnimations.posVec(1.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(3.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_brow", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -5.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_brow", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -0.2F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_brow", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 5.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_brow", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -0.2F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("Spear", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(5.7993F, 4.4922F, -43.2946F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("Shield", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(-25.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.build();

	public static final AnimationDefinition WALK = AnimationDefinition.Builder.withLength(0.75F).looping()
			.addAnimation("Guard", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -0.5F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.125F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.25F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.375F, KeyframeAnimations.posVec(0.0F, -0.5F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.625F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.75F, KeyframeAnimations.posVec(0.0F, -0.5F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("Body", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(3.73F, 0.43F, -4.96F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.125F, KeyframeAnimations.degreeVec(-2.5F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.25F, KeyframeAnimations.degreeVec(9.9627F, -0.8672F, 4.9244F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.375F, KeyframeAnimations.degreeVec(3.73F, -0.43F, 4.96F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5F, KeyframeAnimations.degreeVec(-2.5F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.625F, KeyframeAnimations.degreeVec(9.9627F, 0.8672F, -4.9244F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.75F, KeyframeAnimations.degreeVec(3.73F, 0.43F, -4.96F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("Body", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -0.52F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.125F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.25F, KeyframeAnimations.posVec(0.0F, -0.7F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.375F, KeyframeAnimations.posVec(0.0F, -0.52F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.625F, KeyframeAnimations.posVec(0.0F, -0.7F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.75F, KeyframeAnimations.posVec(0.0F, -0.52F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("Head", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(-3.74F, 0.27F, 1.22F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.125F, KeyframeAnimations.degreeVec(2.5F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.25F, KeyframeAnimations.degreeVec(-9.9885F, -0.5409F, -2.4408F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.375F, KeyframeAnimations.degreeVec(-3.74F, -0.27F, -1.22F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5F, KeyframeAnimations.degreeVec(2.5F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.625F, KeyframeAnimations.degreeVec(-9.9885F, 0.5409F, 2.4408F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.75F, KeyframeAnimations.degreeVec(-3.74F, 0.27F, 1.22F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("Cape", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(20.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.25F, KeyframeAnimations.degreeVec(30.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.375F, KeyframeAnimations.degreeVec(20.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.625F, KeyframeAnimations.degreeVec(30.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.75F, KeyframeAnimations.degreeVec(20.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("RightArm", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(16.4486F, 19.6632F, 28.5941F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.125F, KeyframeAnimations.degreeVec(16.4486F, 19.6632F, 28.5941F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.25F, KeyframeAnimations.degreeVec(23.746F, 19.0377F, 18.5484F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5F, KeyframeAnimations.degreeVec(23.746F, 19.0377F, 18.5484F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.625F, KeyframeAnimations.degreeVec(16.4486F, 19.6632F, 28.5941F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.75F, KeyframeAnimations.degreeVec(16.4486F, 19.6632F, 28.5941F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("LeftArm", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(-70.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("RightLeg", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(2.5F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.125F, KeyframeAnimations.degreeVec(10.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.375F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5F, KeyframeAnimations.degreeVec(-17.5F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.625F, KeyframeAnimations.degreeVec(-7.5F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.75F, KeyframeAnimations.degreeVec(2.5F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("RightLeg", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, -0.5F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.125F, KeyframeAnimations.posVec(0.0F, 0.0F, 2.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.375F, KeyframeAnimations.posVec(0.0F, 2.0F, -2.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5F, KeyframeAnimations.posVec(0.0F, 2.0F, -2.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.625F, KeyframeAnimations.posVec(0.0F, 0.0F, -4.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.75F, KeyframeAnimations.posVec(0.0F, 0.0F, -0.5F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("LeftLeg", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.125F, KeyframeAnimations.degreeVec(-17.5F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.25F, KeyframeAnimations.degreeVec(-7.5F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5F, KeyframeAnimations.degreeVec(10.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.75F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("LeftLeg", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 2.0F, -2.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.125F, KeyframeAnimations.posVec(0.0F, 2.0F, -2.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.25F, KeyframeAnimations.posVec(0.0F, 0.0F, -4.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.375F, KeyframeAnimations.posVec(0.0F, 0.0F, -0.5F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5F, KeyframeAnimations.posVec(0.0F, 0.0F, 3.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.75F, KeyframeAnimations.posVec(0.0F, 2.0F, -2.0F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("left_brow", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -5.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_brow", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -0.2F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_brow", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 5.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_brow", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -0.2F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("Spear", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(5.7993F, 4.4922F, -43.2946F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("Shield", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(-20.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.build();

	public static final AnimationDefinition ATTACK = AnimationDefinition.Builder.withLength(1.25F)
			.addAnimation("Body", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.125F, KeyframeAnimations.degreeVec(-5.0F, 20.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5F, KeyframeAnimations.degreeVec(-5.0F, 20.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.625F, KeyframeAnimations.degreeVec(15.0F, -17.5F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.0F, KeyframeAnimations.degreeVec(10.0F, -17.5F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.125F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("Body", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.625F, KeyframeAnimations.posVec(0.0F, -1.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("Head", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.125F, KeyframeAnimations.degreeVec(5.0F, -17.5F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5F, KeyframeAnimations.degreeVec(5.0F, -17.5F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.625F, KeyframeAnimations.degreeVec(-12.291F, 20.0583F, 0.5759F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.0F, KeyframeAnimations.degreeVec(-7.5F, 22.5F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.125F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("Cape", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(15.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.125F, KeyframeAnimations.degreeVec(15.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5F, KeyframeAnimations.degreeVec(15.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.7083F, KeyframeAnimations.degreeVec(37.5F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.0F, KeyframeAnimations.degreeVec(15.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("RightArm", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(6.25F, 19.04F, 18.55F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.125F, KeyframeAnimations.degreeVec(54.1345F, -11.116F, 72.6723F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5F, KeyframeAnimations.degreeVec(54.1345F, -11.116F, 72.6723F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.625F, KeyframeAnimations.degreeVec(-34.829F, 12.1444F, 84.6939F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.7083F, KeyframeAnimations.degreeVec(-47.9564F, 13.1673F, 89.5794F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.125F, KeyframeAnimations.degreeVec(6.246F, 19.0377F, 18.5484F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("LeftArm", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(-62.5F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.125F, KeyframeAnimations.degreeVec(-63.4901F, -25.0147F, -5.44F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5F, KeyframeAnimations.degreeVec(-63.49F, -25.01F, -5.44F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.625F, KeyframeAnimations.degreeVec(-71.526F, -38.1892F, -13.8921F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.0F, KeyframeAnimations.degreeVec(-71.53F, -38.19F, -13.89F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.125F, KeyframeAnimations.degreeVec(-62.5F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("RightLeg", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(6.5455F, 16.9967F, 5.209F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.125F, KeyframeAnimations.degreeVec(10.0F, 50.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5F, KeyframeAnimations.degreeVec(10.0F, 50.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5833F, KeyframeAnimations.degreeVec(-23.7316F, 30.5839F, -4.6981F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.625F, KeyframeAnimations.degreeVec(0.0F, 17.5F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.0F, KeyframeAnimations.degreeVec(0.0F, 17.5F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.125F, KeyframeAnimations.degreeVec(6.5455F, 16.9967F, 5.209F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("RightLeg", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.125F, KeyframeAnimations.posVec(0.0F, 0.0F, 3.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5F, KeyframeAnimations.posVec(0.0F, 0.0F, 3.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5833F, KeyframeAnimations.posVec(0.0F, 2.0F, -1.93F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.625F, KeyframeAnimations.posVec(0.0F, 0.0F, -4.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.0F, KeyframeAnimations.posVec(0.0F, 0.0F, -4.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.0417F, KeyframeAnimations.posVec(0.0F, 2.0F, -2.33F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.125F, KeyframeAnimations.posVec(0.0F, 0.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("LeftLeg", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.4583F, KeyframeAnimations.degreeVec(0.0F, -7.5F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5833F, KeyframeAnimations.degreeVec(20.9991F, -25.0231F, -7.8963F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.875F, KeyframeAnimations.degreeVec(20.9991F, -25.0231F, -7.8963F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.0F, KeyframeAnimations.degreeVec(0.0F, -7.5F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("LeftLeg", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.4583F, KeyframeAnimations.posVec(1.0F, 0.0F, -2.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5833F, KeyframeAnimations.posVec(1.0F, 0.0F, 1.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.875F, KeyframeAnimations.posVec(1.0F, 0.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.9583F, KeyframeAnimations.posVec(1.0F, 1.0F, -1.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.0F, KeyframeAnimations.posVec(1.0F, 0.0F, -2.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("r_eye", new AnimationChannel(AnimationChannel.Targets.SCALE,
					new Keyframe(0.0F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.25F, KeyframeAnimations.scaleVec(1.0F, 0.8F, 1.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.875F, KeyframeAnimations.scaleVec(1.0F, 0.8F, 1.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.125F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_brow", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -5.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_brow", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -0.2F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_brow", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 5.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.25F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 7.5F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.875F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 7.5F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.125F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 5.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_brow", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -0.2F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.25F, KeyframeAnimations.posVec(0.0F, -0.5F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.875F, KeyframeAnimations.posVec(0.0F, -0.5F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.125F, KeyframeAnimations.posVec(0.0F, -0.2F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("Spear", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(5.7993F, 4.4922F, -43.2946F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.125F, KeyframeAnimations.degreeVec(6.8878F, 32.3503F, 7.3838F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5F, KeyframeAnimations.degreeVec(6.8878F, 32.3503F, 7.3838F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.625F, KeyframeAnimations.degreeVec(-4.1894F, -46.2318F, 7.8993F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.7083F, KeyframeAnimations.degreeVec(-4.4219F, -63.6832F, 9.228F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.125F, KeyframeAnimations.degreeVec(5.7993F, 4.4922F, -43.2946F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("Shield", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(-25.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.build();

	public static final AnimationDefinition SHIELD_BREAK = AnimationDefinition.Builder.withLength(1.6009F)
			.addAnimation("Body", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.0781F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.2343F, KeyframeAnimations.degreeVec(10.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.3905F, KeyframeAnimations.degreeVec(22.5F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.4295F, KeyframeAnimations.degreeVec(25.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5467F, KeyframeAnimations.degreeVec(15.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.7028F, KeyframeAnimations.degreeVec(22.5F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.7419F, KeyframeAnimations.degreeVec(25.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.859F, KeyframeAnimations.degreeVec(15.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.0152F, KeyframeAnimations.degreeVec(22.5F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.0543F, KeyframeAnimations.degreeVec(25.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.2495F, KeyframeAnimations.degreeVec(22.5F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.3666F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.4838F, KeyframeAnimations.degreeVec(31.054F, 44.7506F, 10.9521F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("Body", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(1.4838F, KeyframeAnimations.posVec(0.0F, -0.52F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("Head", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.1562F, KeyframeAnimations.degreeVec(10.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.3124F, KeyframeAnimations.degreeVec(5.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.4686F, KeyframeAnimations.degreeVec(10.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.6248F, KeyframeAnimations.degreeVec(5.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.7809F, KeyframeAnimations.degreeVec(10.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.9371F, KeyframeAnimations.degreeVec(5.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.0933F, KeyframeAnimations.degreeVec(10.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.2495F, KeyframeAnimations.degreeVec(10.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.3666F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.4838F, KeyframeAnimations.degreeVec(-24.7549F, -44.1817F, 12.5832F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("Cape", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(15.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.2733F, KeyframeAnimations.degreeVec(10.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.4295F, KeyframeAnimations.degreeVec(35.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5857F, KeyframeAnimations.degreeVec(22.5F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.7419F, KeyframeAnimations.degreeVec(35.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.8981F, KeyframeAnimations.degreeVec(22.5F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.0543F, KeyframeAnimations.degreeVec(35.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.2886F, KeyframeAnimations.degreeVec(15.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.4838F, KeyframeAnimations.degreeVec(25.3442F, -4.4462F, 9.9539F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("RightArm", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(6.246F, 19.0377F, 18.5484F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.1562F, KeyframeAnimations.degreeVec(-47.4119F, 14.9854F, 0.6696F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.3124F, KeyframeAnimations.degreeVec(-104.9119F, 14.9854F, 0.6696F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.4686F, KeyframeAnimations.degreeVec(-47.4119F, 14.9854F, 0.6696F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.6248F, KeyframeAnimations.degreeVec(-104.9119F, 14.9854F, 0.6696F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.7809F, KeyframeAnimations.degreeVec(-47.4119F, 14.9854F, 0.6696F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.9371F, KeyframeAnimations.degreeVec(-104.9119F, 14.9854F, 0.6696F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.0933F, KeyframeAnimations.degreeVec(-47.4119F, 14.9854F, 0.6696F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.2495F, KeyframeAnimations.degreeVec(-47.4119F, 14.9854F, 0.6696F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.3666F, KeyframeAnimations.degreeVec(6.246F, 19.0377F, 18.5484F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.4838F, KeyframeAnimations.degreeVec(-15.6928F, -16.8855F, 19.6653F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("RightArm", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.2886F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("LeftArm", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(-62.5F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.3124F, KeyframeAnimations.degreeVec(-2.0833F, 4.8132F, -31.7893F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.4686F, KeyframeAnimations.degreeVec(-3.936F, 5.0438F, -24.265F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.6248F, KeyframeAnimations.degreeVec(-2.0833F, 4.8132F, -31.7893F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.7809F, KeyframeAnimations.degreeVec(-3.936F, 5.0438F, -24.265F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.9371F, KeyframeAnimations.degreeVec(-2.0833F, 4.8132F, -31.7893F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.0933F, KeyframeAnimations.degreeVec(-3.936F, 5.0438F, -24.265F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.2495F, KeyframeAnimations.degreeVec(-3.936F, 5.0438F, -24.265F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.4057F, KeyframeAnimations.degreeVec(-62.5F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.4838F, KeyframeAnimations.degreeVec(-54.5352F, -11.9273F, 50.3621F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("LeftArm", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(1.4838F, KeyframeAnimations.posVec(-0.2053F, -0.3629F, -0.9089F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("RightLeg", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(6.5455F, 16.9967F, 5.209F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.0781F, KeyframeAnimations.degreeVec(-10.0F, 12.5F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.2343F, KeyframeAnimations.degreeVec(-7.5F, 12.5F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.3905F, KeyframeAnimations.degreeVec(-10.0F, 12.5F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5467F, KeyframeAnimations.degreeVec(-7.5F, 12.5F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.7028F, KeyframeAnimations.degreeVec(-10.0F, 12.5F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.859F, KeyframeAnimations.degreeVec(-7.5F, 12.5F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.0152F, KeyframeAnimations.degreeVec(-10.0F, 12.5F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.2495F, KeyframeAnimations.degreeVec(-10.0F, 12.5F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.3666F, KeyframeAnimations.degreeVec(6.5455F, 16.9967F, 5.209F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.4838F, KeyframeAnimations.degreeVec(8.75F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("RightLeg", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 1.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.2733F, KeyframeAnimations.posVec(-1.0F, 4.0F, -4.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.3905F, KeyframeAnimations.posVec(-1.0F, -0.75F, -4.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.4295F, KeyframeAnimations.posVec(-1.0F, 0.0F, -4.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5857F, KeyframeAnimations.posVec(-1.0F, 4.0F, -4.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.7028F, KeyframeAnimations.posVec(-1.0F, -0.75F, -4.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.7419F, KeyframeAnimations.posVec(-1.0F, 0.0F, -4.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.8981F, KeyframeAnimations.posVec(-1.0F, 4.0F, -4.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.0152F, KeyframeAnimations.posVec(-1.0F, -0.75F, -4.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.0543F, KeyframeAnimations.posVec(-1.0F, 0.0F, -4.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.2495F, KeyframeAnimations.posVec(-1.0F, 0.0F, -4.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.3276F, KeyframeAnimations.posVec(-0.3F, 1.0F, -0.48F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.4057F, KeyframeAnimations.posVec(0.0F, 0.0F, 1.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.4838F, KeyframeAnimations.posVec(0.0F, 0.0F, -0.5F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("LeftLeg", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, -7.5F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.1562F, KeyframeAnimations.degreeVec(9.99F, -12.1533F, -7.0496F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.1714F, KeyframeAnimations.degreeVec(9.99F, -12.1533F, -7.0496F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.2886F, KeyframeAnimations.degreeVec(0.0F, -7.5F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.4838F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("LeftLeg", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(1.0F, 0.0F, -2.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.0781F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.1714F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.2886F, KeyframeAnimations.posVec(1.0F, 0.0F, -2.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.4838F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("Guard", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(1.4838F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("left_brow", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -5.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.0781F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -10.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.1714F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -10.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.2886F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -5.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.4838F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -5.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_brow", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -0.2F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.0781F, KeyframeAnimations.posVec(0.0F, -0.6F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.1714F, KeyframeAnimations.posVec(0.0F, -0.6F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.2886F, KeyframeAnimations.posVec(0.0F, -0.2F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.4838F, KeyframeAnimations.posVec(0.0F, -0.5F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_brow", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 5.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.0781F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 10.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.1714F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 10.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.2886F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 5.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.4838F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 5.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_brow", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -0.2F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.0781F, KeyframeAnimations.posVec(0.0F, -0.6F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.1714F, KeyframeAnimations.posVec(0.0F, -0.6F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.2886F, KeyframeAnimations.posVec(0.0F, -0.2F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.4838F, KeyframeAnimations.posVec(0.0F, -0.5F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("Spear", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(5.7993F, 4.4922F, -43.2946F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.1562F, KeyframeAnimations.degreeVec(-2.1518F, 4.7694F, -1.0397F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.2495F, KeyframeAnimations.degreeVec(-2.1518F, 4.7694F, -1.0397F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.3666F, KeyframeAnimations.degreeVec(5.7993F, 4.4922F, -43.2946F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.4838F, KeyframeAnimations.degreeVec(-48.5741F, 2.0351F, -53.9958F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("Shield", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(-25.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(1.4838F, KeyframeAnimations.degreeVec(-5.0F, 0.0F, -80.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("Shield", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(1.4838F, KeyframeAnimations.posVec(2.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.build();

	public static final AnimationDefinition CHARGE = AnimationDefinition.Builder.withLength(0.5F).looping()
			.addAnimation("Guard", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.0833F, KeyframeAnimations.posVec(0.0F, 0.5F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.1667F, KeyframeAnimations.posVec(0.0F, -0.3F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.25F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.3333F, KeyframeAnimations.posVec(0.0F, 0.5F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.4167F, KeyframeAnimations.posVec(0.0F, -0.3F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("Body", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(31.054F, 44.7506F, 10.9521F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.0833F, KeyframeAnimations.degreeVec(25.1929F, 50.3546F, 7.8339F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.1667F, KeyframeAnimations.degreeVec(25.1929F, 50.3546F, 10.3339F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.25F, KeyframeAnimations.degreeVec(31.054F, 44.7506F, 10.9521F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.3333F, KeyframeAnimations.degreeVec(25.1929F, 40.3546F, 7.8339F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.4167F, KeyframeAnimations.degreeVec(25.1929F, 40.3546F, 10.3339F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5F, KeyframeAnimations.degreeVec(31.054F, 44.7506F, 10.9521F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("Body", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -0.52F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.0833F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.1667F, KeyframeAnimations.posVec(0.0F, -1.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.25F, KeyframeAnimations.posVec(0.0F, -0.52F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.3333F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.4167F, KeyframeAnimations.posVec(0.0F, -1.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5F, KeyframeAnimations.posVec(0.0F, -0.52F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("Head", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(-24.7549F, -44.1817F, 12.5832F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.0833F, KeyframeAnimations.degreeVec(-24.7549F, -49.1817F, 12.5832F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.1667F, KeyframeAnimations.degreeVec(-24.7549F, -49.1817F, 12.5832F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.25F, KeyframeAnimations.degreeVec(-24.7549F, -44.1817F, 12.5832F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.3333F, KeyframeAnimations.degreeVec(-24.7549F, -39.1817F, 12.5832F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.4167F, KeyframeAnimations.degreeVec(-24.7549F, -39.1817F, 12.5832F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5F, KeyframeAnimations.degreeVec(-24.7549F, -44.1817F, 12.5832F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("Cape", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(25.3442F, -4.4462F, 9.9539F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.0833F, KeyframeAnimations.degreeVec(35.4767F, -2.9975F, 7.9121F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.1667F, KeyframeAnimations.degreeVec(20.3442F, -4.4462F, 9.9539F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.25F, KeyframeAnimations.degreeVec(25.3442F, -4.4462F, 9.9539F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.3333F, KeyframeAnimations.degreeVec(35.1595F, -5.8893F, 12.0038F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.4167F, KeyframeAnimations.degreeVec(20.3442F, -4.4462F, 9.9539F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.4722F, KeyframeAnimations.degreeVec(-24.7549F, -44.1817F, 12.5832F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5F, KeyframeAnimations.degreeVec(25.3442F, -4.4462F, 9.9539F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("RightArm", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(-15.6928F, -16.8855F, 19.6653F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("LeftArm", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(-54.5352F, -11.9273F, 50.3621F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("LeftArm", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(-0.2053F, -0.3629F, -0.9089F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("RightLeg", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(8.75F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.0833F, KeyframeAnimations.degreeVec(22.5F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.25F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.3333F, KeyframeAnimations.degreeVec(-22.5F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.4167F, KeyframeAnimations.degreeVec(-15.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5F, KeyframeAnimations.degreeVec(8.75F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("RightLeg", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, -0.5F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.0833F, KeyframeAnimations.posVec(0.0F, 0.0F, 2.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.25F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.3333F, KeyframeAnimations.posVec(0.0F, 2.0F, -2.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.4167F, KeyframeAnimations.posVec(0.0F, 0.0F, -4.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5F, KeyframeAnimations.posVec(0.0F, 0.0F, -0.5F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("LeftLeg", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.0833F, KeyframeAnimations.degreeVec(-22.5F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.1667F, KeyframeAnimations.degreeVec(-15.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.3333F, KeyframeAnimations.degreeVec(22.5F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("LeftLeg", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.0833F, KeyframeAnimations.posVec(0.0F, 2.0F, -2.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.1667F, KeyframeAnimations.posVec(0.0F, 0.0F, -4.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.3333F, KeyframeAnimations.posVec(0.0F, 0.0F, 2.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("left_brow", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -5.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_brow", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -0.5F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_brow", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 5.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_brow", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -0.5F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("Spear", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(-48.5741F, 2.0351F, -53.9958F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("Shield", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(-5.0F, 0.0F, -80.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("Shield", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(2.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.build();

	public static final AnimationDefinition CHARGE_COLLIDED_STOP = AnimationDefinition.Builder.withLength(1.0417F)
			.addAnimation("Guard", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.125F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.25F, KeyframeAnimations.degreeVec(-4.8331F, 0.7865F, -1.0455F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("Body", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(31.054F, 44.7506F, 10.9521F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.125F, KeyframeAnimations.degreeVec(42.0799F, 41.9498F, 18.2458F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.25F, KeyframeAnimations.degreeVec(2.4064F, 25.0502F, 0.5569F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.375F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5F, KeyframeAnimations.degreeVec(2.5F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.625F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("Body", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -0.52F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.125F, KeyframeAnimations.posVec(0.0F, -0.52F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.25F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("Head", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(-24.7549F, -44.1817F, 12.5832F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.1667F, KeyframeAnimations.degreeVec(-10.6282F, -34.3785F, 10.0236F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.2917F, KeyframeAnimations.degreeVec(-3.9227F, -16.6324F, 0.3449F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.4167F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5417F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("Cape", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(25.3442F, -4.4462F, 9.9539F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.125F, KeyframeAnimations.degreeVec(10.3442F, -4.4462F, 9.9539F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.2917F, KeyframeAnimations.degreeVec(45.3442F, -4.4462F, 9.9539F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5417F, KeyframeAnimations.degreeVec(15.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("RightArm", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(-15.6928F, -16.8855F, 19.6653F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.1667F, KeyframeAnimations.degreeVec(-15.69F, -16.89F, 19.67F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.2917F, KeyframeAnimations.degreeVec(16.9234F, 30.8994F, 35.4649F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.4167F, KeyframeAnimations.degreeVec(18.4432F, 25.1845F, 38.7419F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5417F, KeyframeAnimations.degreeVec(6.246F, 19.0377F, 18.5484F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("RightArm", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.1667F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.2917F, KeyframeAnimations.posVec(0.0F, 1.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.6667F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.7917F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("LeftArm", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(-54.5352F, -11.9273F, 50.3621F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.1667F, KeyframeAnimations.degreeVec(-54.5352F, -11.9273F, 50.3621F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.2917F, KeyframeAnimations.degreeVec(-86.5942F, -51.5483F, -1.5347F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.4583F, KeyframeAnimations.degreeVec(-64.05F, -28.25F, -4.01F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.625F, KeyframeAnimations.degreeVec(-62.5F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("LeftArm", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(-0.2053F, -0.3629F, -0.9089F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("RightLeg", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(8.75F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.0833F, KeyframeAnimations.degreeVec(22.5F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.25F, KeyframeAnimations.degreeVec(22.5F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.375F, KeyframeAnimations.degreeVec(22.5F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5417F, KeyframeAnimations.degreeVec(6.55F, 17.0F, 5.21F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("RightLeg", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, -0.5F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.0833F, KeyframeAnimations.posVec(0.0F, 0.0F, 2.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.25F, KeyframeAnimations.posVec(0.0F, 0.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.375F, KeyframeAnimations.posVec(0.0F, 0.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5417F, KeyframeAnimations.posVec(0.0F, 0.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("LeftLeg", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.0833F, KeyframeAnimations.degreeVec(-22.5F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.1667F, KeyframeAnimations.degreeVec(-15.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.25F, KeyframeAnimations.degreeVec(-22.5F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.375F, KeyframeAnimations.degreeVec(-22.5F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5417F, KeyframeAnimations.degreeVec(0.0F, -7.5F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("LeftLeg", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.0833F, KeyframeAnimations.posVec(0.0F, 2.0F, -2.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.1667F, KeyframeAnimations.posVec(0.0F, 0.0F, -4.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.25F, KeyframeAnimations.posVec(0.0F, -1.0F, -3.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.375F, KeyframeAnimations.posVec(0.0F, -1.0F, -3.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.4583F, KeyframeAnimations.posVec(1.0F, 1.0F, -2.33F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5417F, KeyframeAnimations.posVec(1.0F, 0.0F, -2.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("r_eye", new AnimationChannel(AnimationChannel.Targets.SCALE,
					new Keyframe(0.0F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.125F, KeyframeAnimations.scaleVec(1.0F, 0.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.25F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("r_eye_white", new AnimationChannel(AnimationChannel.Targets.SCALE,
					new Keyframe(0.125F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.25F, KeyframeAnimations.scaleVec(1.0F, 1.4F, 1.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("l_eye", new AnimationChannel(AnimationChannel.Targets.SCALE,
					new Keyframe(0.0F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.125F, KeyframeAnimations.scaleVec(1.0F, 0.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.25F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("l_eye_white", new AnimationChannel(AnimationChannel.Targets.SCALE,
					new Keyframe(0.125F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.25F, KeyframeAnimations.scaleVec(1.0F, 1.4F, 1.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_brow", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -5.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.25F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -5.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_brow", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -0.5F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.125F, KeyframeAnimations.posVec(0.0F, -0.5F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.25F, KeyframeAnimations.posVec(0.0F, 0.4F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5F, KeyframeAnimations.posVec(0.0F, -0.2F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_brow", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 5.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.25F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_brow", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -0.5F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.125F, KeyframeAnimations.posVec(0.0F, -0.5F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.25F, KeyframeAnimations.posVec(0.0F, 0.4F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5F, KeyframeAnimations.posVec(0.0F, -0.2F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("Spear", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(-48.5741F, 2.0351F, -53.9958F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.125F, KeyframeAnimations.degreeVec(-48.57F, 2.04F, -54.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.25F, KeyframeAnimations.degreeVec(3.6929F, -6.7644F, -7.3674F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5F, KeyframeAnimations.degreeVec(5.7993F, 4.4922F, -43.2946F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("Shield", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(-5.0F, 0.0F, -80.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.1667F, KeyframeAnimations.degreeVec(-5.0F, 0.0F, -80.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.2917F, KeyframeAnimations.degreeVec(-10.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5417F, KeyframeAnimations.degreeVec(-25.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("Shield", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(2.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.1667F, KeyframeAnimations.posVec(2.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.2917F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.build();

	public static final AnimationDefinition CHARGE_NORMAL_STOP = AnimationDefinition.Builder.withLength(1.087F)
			.addAnimation("Guard", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.1449F, KeyframeAnimations.degreeVec(-2.5F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.3261F, KeyframeAnimations.degreeVec(-2.5F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.471F, KeyframeAnimations.degreeVec(5.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.6522F, KeyframeAnimations.degreeVec(5.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.7971F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("Body", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(31.054F, 44.7506F, 10.9521F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.1812F, KeyframeAnimations.degreeVec(9.07F, 35.6F, 3.79F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.3261F, KeyframeAnimations.degreeVec(-3.2301F, 26.9673F, -0.4653F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.471F, KeyframeAnimations.degreeVec(15.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.6884F, KeyframeAnimations.degreeVec(-7.5F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.9058F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("Body", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -0.52F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.3261F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.471F, KeyframeAnimations.posVec(0.0F, 0.0F, -1.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.6522F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("Head", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(-24.7549F, -44.1817F, 12.5832F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.1812F, KeyframeAnimations.degreeVec(-13.0F, -34.83F, 6.21F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.3261F, KeyframeAnimations.degreeVec(-4.2726F, -26.1714F, 2.1184F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5797F, KeyframeAnimations.degreeVec(10.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.7609F, KeyframeAnimations.degreeVec(-7.5F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.942F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("Cape", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(25.3442F, -4.4462F, 9.9539F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.3261F, KeyframeAnimations.degreeVec(12.8442F, -4.4462F, 9.9539F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5435F, KeyframeAnimations.degreeVec(45.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.8696F, KeyframeAnimations.degreeVec(15.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("RightArm", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(-15.6928F, -16.8855F, 19.6653F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.1812F, KeyframeAnimations.degreeVec(-53.58F, -25.23F, 28.61F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.3261F, KeyframeAnimations.degreeVec(-65.6715F, -23.6901F, 33.9335F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.6159F, KeyframeAnimations.degreeVec(27.3943F, 33.1888F, 33.3463F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.8333F, KeyframeAnimations.degreeVec(6.25F, 19.04F, 18.55F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("LeftArm", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(-54.5352F, -11.9273F, 50.3621F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.1812F, KeyframeAnimations.degreeVec(-96.9F, -14.63F, 56.8F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.3261F, KeyframeAnimations.degreeVec(-112.5166F, -16.5546F, 52.317F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5072F, KeyframeAnimations.degreeVec(-26.5734F, -19.0568F, -20.2085F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.6884F, KeyframeAnimations.degreeVec(-63.5968F, 7.9813F, -15.6249F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.8696F, KeyframeAnimations.degreeVec(-62.5F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("LeftArm", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(-0.2053F, -0.3629F, -0.9089F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("RightLeg", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(8.75F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.1812F, KeyframeAnimations.degreeVec(6.25F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.3261F, KeyframeAnimations.degreeVec(6.25F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.471F, KeyframeAnimations.degreeVec(-18.75F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.6522F, KeyframeAnimations.degreeVec(-18.75F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.7971F, KeyframeAnimations.degreeVec(6.5455F, 16.9967F, 5.209F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("RightLeg", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, -0.5F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.1812F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.5F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.3261F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.5F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.3986F, KeyframeAnimations.posVec(0.0F, 1.0F, -1.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.471F, KeyframeAnimations.posVec(0.0F, 0.0F, -2.5F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.6522F, KeyframeAnimations.posVec(0.0F, 0.0F, -2.5F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.7971F, KeyframeAnimations.posVec(0.0F, 0.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("LeftLeg", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.1449F, KeyframeAnimations.degreeVec(-22.4807F, -0.9564F, -2.3099F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.3261F, KeyframeAnimations.degreeVec(-24.9807F, -0.9564F, -2.3099F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.471F, KeyframeAnimations.degreeVec(5.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.6522F, KeyframeAnimations.degreeVec(5.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.7609F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("LeftLeg", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.1087F, KeyframeAnimations.posVec(0.0F, -0.5F, -2.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.3261F, KeyframeAnimations.posVec(0.0F, -0.5F, -1.5F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.3986F, KeyframeAnimations.posVec(0.5F, 1.0F, -0.94F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.471F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.6522F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.7609F, KeyframeAnimations.posVec(1.0F, 0.0F, -2.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("r_eye", new AnimationChannel(AnimationChannel.Targets.SCALE,
					new Keyframe(0.3261F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5435F, KeyframeAnimations.scaleVec(1.0F, 0.0F, 1.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.7246F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("l_eye", new AnimationChannel(AnimationChannel.Targets.SCALE,
					new Keyframe(0.3261F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5435F, KeyframeAnimations.scaleVec(1.0F, 0.0F, 1.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.7246F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_brow", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -5.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.2536F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.7246F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -5.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_brow", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -0.5F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.2536F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.7246F, KeyframeAnimations.posVec(0.0F, -0.2F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_brow", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 5.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.2536F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5435F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.7246F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 5.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_brow", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -0.5F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.2536F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.5435F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.7246F, KeyframeAnimations.posVec(0.0F, -0.2F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("Spear", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(-48.5741F, 2.0351F, -53.9958F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.1812F, KeyframeAnimations.degreeVec(-46.79F, -3.65F, -46.39F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.3261F, KeyframeAnimations.degreeVec(-40.4859F, -6.9155F, -42.0969F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.6159F, KeyframeAnimations.degreeVec(4.8818F, -5.465F, -44.5982F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.8333F, KeyframeAnimations.degreeVec(5.8F, 4.49F, -43.29F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("Shield", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(-5.0F, 0.0F, -80.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.4348F, KeyframeAnimations.degreeVec(-5.0F, 0.0F, -80.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.6884F, KeyframeAnimations.degreeVec(-25.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("Shield", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(2.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.4348F, KeyframeAnimations.posVec(2.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.6884F, KeyframeAnimations.posVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.build();

	public static final AnimationDefinition STANDING_BY = AnimationDefinition.Builder.withLength(2.0F).looping()
			.addAnimation("Body", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.0F, KeyframeAnimations.degreeVec(2.5F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("Body", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -4.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("Head", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("Cape", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(25.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("RightArm", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(15.3472F, 12.0675F, 25.784F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.25F, KeyframeAnimations.degreeVec(17.8981F, 11.9128F, 26.314F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.0F, KeyframeAnimations.degreeVec(15.3472F, 12.0675F, 25.784F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("LeftArm", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(-67.0099F, -11.5349F, -4.8493F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.0F, KeyframeAnimations.degreeVec(-69.5099F, -11.5349F, -4.8493F),
							AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.0F, KeyframeAnimations.degreeVec(-67.0099F, -11.5349F, -4.8493F),
							AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("RightLeg", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(65.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("RightLeg", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(-0.1F, -5.0F, -2.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("LeftLeg", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(0.1F, 0.0F, -4.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("r_eye", new AnimationChannel(AnimationChannel.Targets.SCALE,
					new Keyframe(0.0F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.125F, KeyframeAnimations.scaleVec(1.0F, 0.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.25F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("l_eye", new AnimationChannel(AnimationChannel.Targets.SCALE,
					new Keyframe(0.0F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.125F, KeyframeAnimations.scaleVec(1.0F, 0.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR),
					new Keyframe(0.25F, KeyframeAnimations.scaleVec(1.0F, 1.0F, 1.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_brow", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -2.5F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("left_brow", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -0.2F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_brow", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 2.5F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("right_brow", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -0.2F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("Spear", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(-8.0805F, -4.6652F, -33.4545F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("Shield", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(-15.0F, 0.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("Shield", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -1.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.build();

	public static final AnimationDefinition SACE = AnimationDefinition.Builder.withLength(0.0F).looping()
			.addAnimation("Shield", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 2.0F, 0.0F),
							AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("Shield", new AnimationChannel(AnimationChannel.Targets.SCALE,
					new Keyframe(0.0F, KeyframeAnimations.scaleVec(1.2F, 1.0F, 1.2F),
							AnimationChannel.Interpolations.LINEAR)))
			.build();
}